from __future__ import annotations

TEXTS = {
    "uz": {
        "choose_language": "Tilni tanlang:",
        "need_subscription": "Botdan foydalanish uchun quyidagi kanallarga obuna bo'ling.",
        "check_subscription": "Obuna bo'ldim",
        "main_menu": "Asosiy menyu",
        "ask": "Savol berish",
        "upload": "Ma'lumot yuklash",
        "my_files": "Mening fayllarim",
        "tariffs": "Tariflar",
        "referrals": "Referal tizimi",
        "history": "Tarix",
        "help": "Yordam",
        "admin": "Admin panel",
        "back": "Orqaga",
        "send_question": "Savolingizni yuboring. Men shaxsiy va ommaviy ma'lumotlardan bir vaqtda qidiraman.",
        "send_upload": "Fayl, rasm, ovoz yoki matn yuboring. Men formatini avtomatik aniqlayman.",
        "save_where": "Qayerga saqlansin?",
        "save_private": "Shaxsiy saqlash",
        "save_public": "Ommaviy saqlash",
        "saved_private": "Ma'lumot shaxsiy bazaga saqlandi.",
        "saved_public_pending": "Ma'lumot ommaviy moderatsiyaga yuborildi.",
        "not_found": "Ma'lumot topilmadi.",
        "about": "ManbaAI — foydalanuvchilar yuklagan ma'lumotlar asosida savollarga javob beradigan sun'iy intellekt botidir. Ushbu loyiha @ManbaAI_admin tomonidan ishlab chiqilgan.",
        "help_text": "Fayl yuklang, savol bering, bot javobni manbalar bilan qaytaradi. Private va public javoblar alohida ko'rsatiladi.",
        "tariffs_text": "Tariflardan birini tanlang.",
        "free_plan": "Free — 3 savol / kun",
        "basic_plan": "Basic — 12 000 so'm / oy, 20 savol / kun",
        "premium_plan": "Premium — 25 000 so'm / oy, yuqori limit",
        "buy_stars": "Stars bilan olish",
        "buy_click": "Click orqali olish",
        "buy_admin": "Admin orqali olish",
        "my_plan": "Mening tarifim",
        "ref_text": "5 ta yangi user taklif qilsangiz, 7 kun Basic olasiz.",
        "rename_file": "Fayl nomini o'zgartirish",
        "delete_file": "Faylni o'chirish",
        "preview_file": "Fayl preview",
        "private_files": "Shaxsiy fayllarim",
        "public_files": "Ommaviy yuklaganlarim",
        "admin_dashboard": "Dashboard",
        "admin_files": "Fayllar boshqaruvi",
        "admin_users": "Foydalanuvchilar",
        "admin_moderation": "Ommaviy moderatsiya",
        "admin_channels": "Kanallar",
        "admin_tariffs": "Tarif boshqaruvi",
        "admin_exports": "Eksport",
        "admin_logs": "Loglar",
        "admin_contact": "Admin bilan bog'lanish",
        "choose_doc_for_rename": "Qaysi fayl nomini o'zgartirmoqchisiz? ID yuboring.",
        "send_new_name": "Yangi fayl nomini yuboring.",
        "choose_doc_for_delete": "Qaysi faylni o'chirmoqchisiz? ID yuboring.",
        "choose_user_for_plan": "User ID yuboring.",
        "choose_channel_id": "Kanal chat_id yoki @username yuboring.",
        "choose_channel_url": "Kanal linkini yuboring.",
        "question_limit_reached": "Bugungi limit tugadi. Tarifni yangilang.",
        "pending_empty": "Pending fayl yo'q.",
        "no_docs": "Fayllar topilmadi.",
        "prompt_id": "ID yuboring.",
        "invalid_id": "ID noto'g'ri.",
        "done": "Bajarildi.",
        "cancelled": "Bekor qilindi.",
        "yes": "Ha",
        "no": "Yo'q",
    },
    "ru": {},
    "en": {},
}

# Fallback copies for non-Uzbek interfaces.
TEXTS["ru"] = TEXTS["uz"].copy()
TEXTS["en"] = TEXTS["uz"].copy()


def t(lang: str, key: str) -> str:
    return TEXTS.get(lang, TEXTS["uz"]).get(key, TEXTS["uz"].get(key, key))
